apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: shared-platform-tools
  labels:
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  # Replace with your actual Slack Bot Token (starts with xoxb-)
  slack-token: ""
